nobase_include_HEADERS = qd/c_dd.h qd/c_qd.h qd/c_td.h \
			 qd/dd_real.h qd/dd_inline.h \
			 qd/fpu.h qd/inline.h qd/qd_real.h qd/qd_inline.h \
			 qd/td_real.h qd/td_inline.h \
			 qd/ds_real.h qd/ts_real.h qd/qs_real.h \
			 qd/fs_inline.h \
			 qd/bits.h

nobase_nodist_include_HEADERS = qd/qd_config.h

DISTCLEANFILES = qd/qd_config.h

